name: Deploy Assets to WordPress.org

on:
  push:
    branches:
      - main
    paths:
      - '.github/.workflows/ASSETS_DEPLOY.yml'
      - 'assets/**'
      - 'banner.png'
      - 'icon-128x128.png'
      - 'icon-256x256.png'

jobs:
  deploy-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Assets to WordPress.org SVN
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: product-quotation-for-woocommerce
